version: '3'

services:
  webserver:
    build: .
    container_name: webserver
    networks:
      - webnet

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
